# Generated by Django 5.2.1 on 2025-07-13 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='doctor_images/')),
                ('experience', models.IntegerField(default='', help_text='Years of experience')),
                ('location', models.CharField(default='', max_length=100)),
                ('clinic_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('response_time', models.IntegerField(blank=True, default='', help_text='Responds in how many minutes', null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('old_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('next_available', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('speciality', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctor.speciality')),
            ],
        ),
    ]
