# Generated by Django 5.2.1 on 2025-07-13 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='next_available',
            new_name='next_available_day',
        ),
    ]
