# Generated by Django 5.2.1 on 2025-07-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_next_available_doctor_next_available_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='next_available_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
