# Generated by Django 5.2.1 on 2025-07-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='online_consultation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
