# Generated by Django 5.2.1 on 2025-07-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_online_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
