# Generated by Django 5.2.1 on 2025-07-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_doctoravailability_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
