# Generated by Django 5.2.1 on 2025-07-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_speciality_slug_alter_speciality_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
