# Generated by Django 5.2.1 on 2025-07-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_alter_speciality_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
