# Generated by Django 5.2.1 on 2025-07-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_appointmentslot_booking_delete_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentslot',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Education 1'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Education 2'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Education 3'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Education 4'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='response_time',
            field=models.IntegerField(blank=True, default=0, help_text='Responds in how many minutes', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentslot',
            unique_together={('doctor', 'date', 'time')},
        ),
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
    ]
