# Generated by Django 5.2.1 on 2025-07-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_alter_appointmentslot_options_doctor_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='patients_treated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
