# Generated by Django 5.2.1 on 2025-07-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_alter_speciality_slug'),
        ('doctor', '0015_doctor_patients_treated'),
    ]

    operations = [
    ]
