# Generated by Django 5.2.1 on 2025-07-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_merge_20250723_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
