# Generated by Django 5.2.1 on 2025-07-26 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_alter_speciality_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_uuid',
            field=models.UUIDField(default='1383d637-5e7e-4d02-a65d-69f8ae7dfb11', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Processing', 'Processing')], default='Pending', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, default='default', max_length=25)),
                ('razorpay_payment_id', models.CharField(blank=True, default='default', max_length=25)),
                ('payment_signature', models.CharField(blank=True, default='default', max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], max_length=25)),
                ('method', models.CharField(choices=[('RAZORPAY', 'RAZORPAY'), ('COD', 'COD'), ('ShopEase_WALLET', 'ShopEase_WALLET')], max_length=25)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctor.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
