# Generated by Django 5.2.1 on 2025-07-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_booking_cancelled_booking_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
