# Generated by Django 6.0.2 on 2026-02-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='other_specialization_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Specialization 1'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='other_specialization_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Specialization 2'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='other_specialization_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Specialization 3'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='other_specialization_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Specialization 4'),
        ),
    ]
